# Generated by Django 3.0 on 2022-02-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_group_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='полное имя')),
                ('topic', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('typescript', 'Typescript'), ('javascript', 'Javascript'), ('ruby', 'Ruby'), ('golang', 'GoLong'), ('sql', 'SQL'), ('swift', 'Swift'), ('php', 'PHP'), ('dephli', 'Dephli'), ('perl', 'Perl')], default='java', max_length=10, verbose_name='предмет')),
                ('students', models.ManyToManyField(to='djangoapp.Student')),
            ],
            options={
                'verbose_name': 'Профессор',
                'verbose_name_plural': 'Профессор',
                'ordering': ('topic',),
            },
        ),
    ]
